server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: ms-pagos-subscripciones

  datasource:
    url: jdbc:postgresql://postgres-pagos:5432/notara-pagos-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  jackson:
    serialization:
      write-dates-as-timestamps: false

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka}
  instance:
    hostname: ms-pagos-subscripciones
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
